"""remove insight columns from users

Revision ID: 3ddf83280b2d
Revises: j0e1f2g3h4i5
Create Date: 2026-03-27 11:37:55.820462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ddf83280b2d'
down_revision: Union[str, None] = 'j0e1f2g3h4i5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'insight_last_date')
    op.drop_column('users', 'insight_refreshes_today')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('insight_refreshes_today', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('insight_last_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
