"""add home_view_mode sex goal body_fat_pct macro_preset to users

Revision ID: 46d2aa804c60
Revises: 9be8751c786f
Create Date: 2026-03-31 12:12:15.743608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46d2aa804c60'
down_revision: Union[str, None] = '9be8751c786f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('home_view_mode', sa.String(), nullable=False, server_default='compact'))
    op.add_column('users', sa.Column('sex', sa.String(), nullable=True))
    op.add_column('users', sa.Column('goal', sa.String(), nullable=True))
    op.add_column('users', sa.Column('body_fat_pct', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('users', sa.Column('macro_preset', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'macro_preset')
    op.drop_column('users', 'body_fat_pct')
    op.drop_column('users', 'goal')
    op.drop_column('users', 'sex')
    op.drop_column('users', 'home_view_mode')
    # ### end Alembic commands ###
