"""drop cat_unlocks table and active_cat column

Revision ID: b6e3c5f59769
Revises: g7b8c9d0e1f2
Create Date: 2026-03-25 12:17:18.083044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6e3c5f59769'
down_revision: Union[str, None] = 'g7b8c9d0e1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cat_unlocks_user_id', table_name='cat_unlocks')
    op.drop_table('cat_unlocks')
    op.alter_column('competition_groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('competition_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('custom_drinks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('daily_points', 'calorie_points',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::smallint"))
    op.alter_column('daily_points', 'logging_points',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::smallint"))
    op.alter_column('daily_points', 'macro_points',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::smallint"))
    op.alter_column('daily_points', 'total_points',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::smallint"))
    op.alter_column('daily_points', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_daily_points_user_date', table_name='daily_points')
    op.create_index(op.f('ix_daily_points_user_id'), 'daily_points', ['user_id'], unique=False)
    op.alter_column('food_entries', 'items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('friendships', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('friendships', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'active_cat')
    op.alter_column('weekly_summaries', 'total_points',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::smallint"))
    op.alter_column('weekly_summaries', 'rank',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('weekly_summaries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_weekly_summaries_group_week', table_name='weekly_summaries')
    op.create_index(op.f('ix_weekly_summaries_group_id'), 'weekly_summaries', ['group_id'], unique=False)
    op.alter_column('weight_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weight_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_weekly_summaries_group_id'), table_name='weekly_summaries')
    op.create_index('idx_weekly_summaries_group_week', 'weekly_summaries', ['group_id', 'week_start'], unique=False)
    op.alter_column('weekly_summaries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('weekly_summaries', 'rank',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.alter_column('weekly_summaries', 'total_points',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::smallint"))
    op.add_column('users', sa.Column('active_cat', sa.VARCHAR(), server_default=sa.text("'whiskers'::character varying"), autoincrement=False, nullable=False))
    op.alter_column('friendships', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('friendships', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('food_entries', 'items',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_index(op.f('ix_daily_points_user_id'), table_name='daily_points')
    op.create_index('idx_daily_points_user_date', 'daily_points', ['user_id', 'date'], unique=False)
    op.alter_column('daily_points', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('daily_points', 'total_points',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::smallint"))
    op.alter_column('daily_points', 'macro_points',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::smallint"))
    op.alter_column('daily_points', 'logging_points',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::smallint"))
    op.alter_column('daily_points', 'calorie_points',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::smallint"))
    op.alter_column('custom_drinks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('competition_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('competition_groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_table('cat_unlocks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cat_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('unlocked_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='cat_unlocks_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='cat_unlocks_pkey'),
    sa.UniqueConstraint('user_id', 'cat_name', name='uq_cat_unlocks_user_cat')
    )
    op.create_index('ix_cat_unlocks_user_id', 'cat_unlocks', ['user_id'], unique=False)
    # ### end Alembic commands ###
